print("Welcome to ArgusOS.")
print("The installer will now commence...")
print("----------------------------------")
textutils.slowPrint("Deleting pre-existing files...")
shell.run("delete","startup.lua")
shell.run("delete","os")
shell.run("delete","menu.lua")
shell.run("delete","back.lua")
print("----------------------------------")
sleep(1)
textutils.slowPrint("Installing files from disk...")
shell.run("cp","disk/os/menu.lua","menu.lua")
shell.run("cp","disk/os/os","os")
shell.run("cp","disk/os/startup.lua","startup.lua")
shell.run("cp","disk/os/back.lua","back.lua")
print("----------------------------------")
disk.eject("top")
disk.eject("bottom")
disk.eject("left")
disk.eject("right")
disk.eject("front")
disk.eject("back")
textutils.slowPrint("OS Rebooting...")
sleep(1)
shell.run("eject.lua")
