shell.run("cd disk")
shell.run("pastebin get LRcKPcUU startup.lua")
shell.run("pastebin get QYmB7gNC install.lua")
shell.run("pastebin get pHnfJbJ0 eject.lua")
shell.run("mkdir os")
shell.run("cd os")
shell.run("pastebin get JHS4Gxwb back.lua")
shell.run("pastebin get CPzkd2TN menu.lua")
shell.run("pastebin get u4ejVYmq startup.lua")
shell.run("mkdir os")
shell.run("cd os")
shell.run("pastebin get VzpK01uY .send.lua")
shell.run("pastebin get QXq7Gqae .programs.lua")
shell.run("pastebin get vbFFBUB7 .receive.lua")
shell.run("pastebin get Cc3GVace .nethelp.lua")
shell.run("pastebin get XWBTdT9T .command.lua")
print("Installer installed on disk")