if fs.exists("disk") == true then
    shell.run("cd disk")
    shell.run("github get https://raw.githubusercontent.com/Artin-13/ArgusOS/main/OS_INSTALL/startup.lua startup.lua")
    shell.run("github get https://raw.githubusercontent.com/Artin-13/ArgusOS/main/OS_INSTALL/install.lua install.lua")
    shell.run("github get https://raw.githubusercontent.com/Artin-13/ArgusOS/main/OS_INSTALL/eject.lua eject.lua")
    shell.run("mkdir os")
    shell.run("cd os")
    shell.run("github get https://raw.githubusercontent.com/Artin-13/ArgusOS/main/OS_INSTALL/os/back.lua back.lua")
    shell.run("github get https://raw.githubusercontent.com/Artin-13/ArgusOS/main/OS_INSTALL/os/menu.lua menu.lua")
    shell.run("github get https://raw.githubusercontent.com/Artin-13/ArgusOS/main/OS_INSTALL/os/startup.lua startup.lua")
    shell.run("mkdir os")
    shell.run("cd os")
    shell.run("github get https://raw.githubusercontent.com/Artin-13/ArgusOS/main/OS_INSTALL/os/os/.send.lua .send.lua")
    shell.run("github get https://raw.githubusercontent.com/Artin-13/ArgusOS/main/OS_INSTALL/os/os/.programs.lua .programs.lua")
    shell.run("github get https://raw.githubusercontent.com/Artin-13/ArgusOS/main/OS_INSTALL/os/os/.receive.lua .receive.lua")
    shell.run("github get https://raw.githubusercontent.com/Artin-13/ArgusOS/main/OS_INSTALL/os/os/.nethelp.lua .nethelp.lua")
    shell.run("github get https://raw.githubusercontent.com/Artin-13/ArgusOS/main/OS_INSTALL/os/os/.command.lua .command.lua")
    shell.run("label set bottom ARGUS_INSTALLER")
    print("Installer installed on disk")
    sleep(5)
    os.reboot()
else
    print("Please put in an empty floppy disk to start the installation")
end
