print("This is the installer for the rednet FTP service.")
print("The installer will now commence...")
print("----------------------------------")
textutils.slowPrint("Deleting pre-existing files...")
shell.run("delete","FTP")
print("----------------------------------")
sleep(1)
textutils.slowPrint("Installing files from disk...")
shell.run("cp","disk/FTP","FTP")
print("----------------------------------")
textutils.slowPrint("OS Rebooting...")
sleep(1)
shell.run("eject.lua")
